name: kasmini_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.1
  lottie: ^3.3.0
  image_picker: ^0.8.8+8
  gap: ^2.0.1
  intl: ^0.18.0
  flutter_calendar_carousel: ^2.1.4

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  sqflite: ^2.4.1
  get_it: ^8.0.3
  path: ^1.9.0
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bgstart.svg
    - assets/images/avatar.jpg
    - assets/images/avatar_placeholder.png
    - assets/images/avatar_female.jpg
    - assets/images/avatar_male.jpg
    - assets/images/male_owner.jpg
    - assets/images/female_owner.jpg
    - assets/images/gitar.png
    - assets/images/pfp.jpeg
    - assets/lottie/start.json
    - assets/lottie/login.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Bold.ttf


